// Landing-page copy moved out of the JSX so editorial tweaks do
// not require touching the layout file. Mirrors the structure of
// `design-system/Martis Docs/src/landing.jsx`.

import type { IconName } from '@/components/icons'

export const STATS: { n: string; l: string }[] = [
  { n: '50',    l: 'Field types' },
  { n: '12',    l: 'Relationship kinds' },
  { n: '94',    l: 'Theme tokens' },
  { n: '1,653', l: 'Tests passing' },
]

export interface FeatureCard {
  ico: IconName
  title: string
  body: string
}

export const FEATURES: FeatureCard[] = [
  { ico: 'Stack',     title: '50 field types',          body: 'Text, select, date, file, code, markdown, sparkline, currency, country, key-value, slug, timezone, icon picker… and 37 more.' },
  { ico: 'Workflow',  title: '12 relationships',        body: 'Every Eloquent relation — BelongsTo to MorphToMany — with inline CRUD, attach/detach, pivot fields, and toolbar flags.' },
  { ico: 'Bolt',      title: 'Reactive forms',          body: 'Field::dependsOn() server-side resolution. Closure-aware setters. Context-aware validation. 4 save variants.' },
  { ico: 'Activity',  title: 'Metrics & dashboards',    body: 'Value, trend, partition, progress, activity feed, endpoint table — query helpers, ranges, caching, auto-refresh.' },
  { ico: 'Filter',    title: 'Filters, lenses & menus', body: 'Per-resource sticky views. Alternative lens queries. Declarative menu API. All feature-complete.' },
  { ico: 'Bolt',      title: 'Actions',                 body: 'Row, bulk, standalone, queued — with confirmation, validation, pivot, custom React, dry-run, per-action icons.' },
  { ico: 'Plug',      title: 'Custom Tools',            body: 'Free-form sidebar pages. Tool::boot() lifecycle. ToolServiceProvider for Composer distribution. martis:tool generator.' },
  { ico: 'Layers',    title: 'Override system',         body: '4-tier component resolution. Replace any view, field, layout, or drawer without forking.' },
  { ico: 'Shield',    title: 'Auth, SSO & 2FA',         body: 'Built-in login. TOTP 2FA. Avatar upload. Azure / Google / GitHub SSO with role mapping.' },
  { ico: 'Palette',   title: '94 theme tokens',         body: 'Comprehensive theme system across 13 categories. Dark + light. Generated by martis:theme.' },
  { ico: 'Translate', title: 'i18n out of the box',     body: 'English, Portuguese (PT) and Portuguese (BR). Per-key deep merge. Configurable fallback chain.' },
  { ico: 'Search',    title: 'Global search',           body: 'Per-resource config. searchOrderBy() hook. "View all N matches" overflow into dedicated results.' },
]

export interface NavLink {
  label: string
  href: string
  external?: boolean
}

export const NAV_LINKS: NavLink[] = [
  { label: 'Docs',       href: '/docs/getting-started/installation' },
  { label: 'Features',   href: '/#features' },
  { label: 'Components', href: '/#components' },
  { label: 'GitHub',     href: 'https://github.com/Real-Edge-FX/martis-package', external: true },
]

export const STACK_ROWS: { k: string; v: string }[] = [
  { k: 'Backend',  v: 'PHP 8.2+ · Laravel 11/12' },
  { k: 'Frontend', v: 'React 18 · TypeScript · PrimeReact · Tailwind' },
  { k: 'Data',     v: 'TanStack Query · React Router' },
  { k: 'Icons',    v: 'Phosphor Icons' },
  { k: 'Build',    v: 'Vite · pnpm' },
  { k: 'Testing',  v: 'Pest · Vitest · PHPStan L8' },
]

export const CODE_SAMPLES = {
  resource: {
    lang: 'php',
    file: 'app/Martis/ClientResource.php',
    code: `<?php

namespace App\\Martis;

use App\\Models\\Client;
use Illuminate\\Http\\Request;
use Martis\\Fields\\{Id, Text, Email, Select, Currency, Badge};
use Martis\\Resource;

class ClientResource extends Resource
{
    public static function model(): string { return Client::class; }

    public function fields(Request $request): array
    {
        return [
            Id::make('id'),
            Text::make('name')->sortable()->searchable()->required(),
            Email::make('email')->sortable()->searchable(),
            Select::make('plan')
                ->options(['free' => 'Free', 'pro' => 'Pro', 'enterprise' => 'Enterprise'])
                ->displayUsingLabels(),
            Currency::make('monthly_revenue')->currency('EUR')->sortable(),
            Badge::make('status')->map([
                'active' => 'success',
                'paused' => 'warning',
                'archived' => 'secondary',
            ]),
        ];
    }
}`,
  },
  metric: {
    lang: 'php',
    file: 'app/Martis/Metrics/TotalRevenue.php',
    code: `<?php

namespace App\\Martis\\Metrics;

use Martis\\Metrics\\Trend;

class TotalRevenue extends Trend
{
    public function name(): string { return 'Total revenue'; }

    public function calculate(Request $request)
    {
        return $this
            ->sumByDays($request, Invoice::class, 'total')
            ->prefix('€')
            ->format('0,0');
    }

    public function ranges(): array
    {
        return [7 => '7 Days', 30 => '30 Days', 90 => '90 Days'];
    }

    public function cacheFor(): int { return 300; }
}`,
  },
  action: {
    lang: 'php',
    file: 'app/Martis/Actions/SendInvoice.php',
    code: `<?php

namespace App\\Martis\\Actions;

use Martis\\Actions\\Action;
use Martis\\Fields\\Email;

class SendInvoice extends Action
{
    public $confirmText = 'Send invoice to selected clients?';
    public $confirmButtonText = 'Send';

    public function fields(): array
    {
        return [
            Email::make('cc')->help('Optional CC recipient'),
        ];
    }

    public function handle(ActionFields $fields, Collection $models)
    {
        foreach ($models as $client) {
            Mail::to($client)->cc($fields->cc)->send(new InvoiceMail($client));
        }
        return Action::message(count($models) . ' invoices sent.');
    }
}`,
  },
} as const

export type CodeSampleKey = keyof typeof CODE_SAMPLES

export const VERSION = 'v1.8.18'
